### ISSUE TITLE
null() call not implemented?

### ISSUE THREAD

**Issue by jrjbertram** [open-dis/open-dis-python#1]
Hi,

Noticed in the code that the null() call doesn't seem to be implemented anywhere.  It looks like it should return an instance of some kind of entity class?  Maybe a RecordSpecificationElement from poking through the code?

I'm specifically seeing this when parsing an EntityStatePdu packet that apparently has some variable parameters, hitting this block in EntityStatePdu.parse(...):
        for idx in range(0, self.numberOfVariableParameters):
            element = null()
            element.parse(inputStream)
            self.variableParameters.append(element)

Is this intentional -- are we supposed to somehow provide a default implementation of null or is this a missing function?

I can get around this by commenting out the lines, which works fine for me as I don't need the variable parameters for what I'm doing.  Thought I'd like you know someone out there ran into it.

Thanks!
- Josh.

**Comment by thekatiemcneil** [comment]
I'm running into this same problem, and needing to set fixedDatums and variableDatums, so commenting out the lines isn't possible for me. Has anyone figured this out?

**Comment by mcgredonps** [comment]
In DIS the "variable parameters" are completely optional. The "Number of Variable Parameter Records" fields tells you how many variable records are present, which should be set when written based on the actual number of parameters.


[cid:50adb220-6457-427c-80b1-3bba2705ebd8]


The list is initialized like this


outputStream.write_unsigned_byte( len(self.variableParameters));

...

 """ a series of bit flags"""

        self.variableParameters = []


In the espdu constructor, which I suspect is wrong. The serialization looks like this:


for anObj in self.variableParameters:

            anObj.serialize(outputStream)



And the deserialized like this:


for idx in range(0, self.numberOfVariableParameters):

            element = null()

            element.parse(inputStream)

            self.variableParameters.append(element)


The idea being to rely on the count in the variable length rather than setting the field directly.


I'm not exactly a Python expert; presumably I should be sticking a 120 byte element of the correct type here?



________________________________

**Comment by mcgredonps** [comment]
Were you able to get the variable parameters working in the dis-python?

________________________________

**Comment by thekatiemcneil** [comment]
Stepped away from this for a bit. I'm just getting back to it, but haven't been able to get it working.

**Comment by aprowe** [comment]
```python
class VariableDatum( object ):

...

    def serialize(self, outputStream):
        """serialize the class """
        outputStream.write_unsigned_int(self.variableDatumID);
        outputStream.write_unsigned_int(self.variableDatumLength);
        outputStream.write_unsigned_int(self.variableDatumBits);

    def parse(self, inputStream):
        """"Parse a message. This may recursively call embedded objects."""

        self.variableDatumID = inputStream.read_unsigned_int();
        self.variableDatumLength = inputStream.read_unsigned_int();
        self.variableDatumBits = inputStream.read_unsigned_int();
```
isn't ` self.variableDatumBits = inputStream.read_unsigned_int();` problematic as well? It is just reading in 4 bytes of an unsigned into instead the variable length. It should just write those bytes directly to the stream. 

I'm pretty confused on the `null()` call as well. It seem's like it should be calls to their respective classes such as `VariableDatum` or `FixedDatum`

**Comment by vmitsuoka** [comment]
Hello. Is anyone still working on this section of code?

**Comment by vmitsuoka** [comment]
I tried this and it seems to work:

for idx in range(0, self.numberOfVariableParameters):
   element = self.parse(inputStream)
   self.variableParameters.append(element)

**Comment by vmitsuoka** [comment]
Now, I'm running into this:

Created UDP socket  3001
Traceback (most recent call last):
  File "dis_receiver.py", line 36, in <module>
    aPdu = pduFactory.createPdu(data);
  File "../distributed_interactive_simulation\PduFactory.py", line 27, in createPdu
    pdu.parse(inputStream)
  File "../distributed_interactive_simulation\dis7.py", line 5203, in parse
    element = self.parse(inputStream)
  File "../distributed_interactive_simulation\dis7.py", line 5199, in parse
    self.deadReckoningParameters.parse(inputStream)
  File "../distributed_interactive_simulation\dis7.py", line 357, in parse
    self.entityLinearAcceleration.parse(inputStream)
  File "../distributed_interactive_simulation\dis7.py", line 1940, in parse
    self.x = inputStream.read_float();
  File "../dis_io\DataInputStream.py", line 29, in read_float
    return struct.unpack('>f', self.stream.read(4))[0]
struct.error: unpack requires a string argument of length 4

**Comment by leif81** [comment]
Hi @vmitsuoka , I'm not aware of anyone else looking into this yet, pull requests are welcome.

**Comment by vmitsuoka** [comment]
I got it to work without the previous error:

        for idx in range(0, self.numberOfVariableParameters):
            element = []
            element.append(inputStream.read_double())
            element.append(inputStream.read_double())
            self.variableParameters.append(element)

**Comment by vmitsuoka** [comment]
PDU location is showing but I don't how much to adjust for the offset:

Received message:  208
Binary data:  =07=01=01=01>l=98=AC=00=D0=00=00k=03=D6=07=00=04=01=04=03=01N =00=00=0B=FE=
=03=01N =00=00=0B=FE=BF=7F;5=BC=F99(>=8F=1DCA44=9E=E8R=D6=99=C1Q=92=FB=04{G=
=B1AO=FE]=89/DO=C0GF=F3=BE=8DA=97@=14=FE\=02=02=00=00=03=00=00=00=00=00=00=
=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=80=00=00=00=
=80=00=00=00=00=00=00=00=01=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=00=
=00=00=00=00=00=10=0C=80=00=00=00=00=00=00=00=00=00=00=00=00=00=10=0B=80=00=
=00=00=00=00=00=00=00=00=00=01=00=00=11N=00=00=00=00=00=00=00=00=00=00=00=
=01=00=00=11M=00=00=00=00=00=00=00=00
self.numberOfVariableParameters:  4
Pdu location is  1324190.90751 -4606956.07002 4193467.07175

MGRS is 18TWL8667080462.

What do you advise?

**Comment by vmitsuoka** [comment]
Does the PDU packet size has to be exactly 250 bytes? VBS3 does not see the Python script broadcast using the dis_udp.py script.

**Comment by spriggsy** [comment]
The packets that I am sending to VBS3 are not 250 bytes so this is not your problem. I found that the pdu.length variable was not being populated when the pdu was being serialised. to get around this I serialised the packet, got the pdulength, inserted this value then re-serialised.


```
memoryStream = BytesIO()
    outputStream = DataOutputStream(memoryStream)
    pdu.serialize(outputStream)
    data = memoryStream.getvalue()

    pduLen = memoryStream.getvalue()
    pdu.length = len(pduLen)

    memoryStream = BytesIO()
    outputStream = DataOutputStream(memoryStream)
    pdu.serialize(outputStream)
    data1 = memoryStream.getvalue()    
    udpSocket.sendto(data1, (DESTINATION_ADDRESS, UDP_PORT))
```

on a side note how have you managed to add variableParameters to your DIS packets??

many thanks

Spriggsy

**Comment by vmitsuoka** [comment]
I haven't looked at the code in a while. I hardcoded it to just grab the entire variableParameters and doing nothing with it. I had success in reading GPS data and sending it into VBS as a PDU. The same with processing broadcasted PDU's and converting it into a readable format for another teammate's HoloLens. I am not sure what I am supposed to use variableParameters for.

**Comment by jmfGE** [comment]
This is still an issue it seems. The variable parameters de-serialization is unimplemented and throws the "NameError: name 'null' is not defined" error.
