### ISSUE TITLE
EntityMarking only serializes 11 of 12 required bytes

### ISSUE THREAD

**Issue by DuffyScottC** [open-dis/open-dis-python#15]
According to the [DIS Data Dictionary on Entity State PDUs](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/29.htm), the Entity Marking Record should be 12 bytes (96 bits) long. 

In [dis7.py line 1351](https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L1351), in the `serialize` method of the `EntityMarking` class, the for loop only loops through 11 list elements:

```py
def serialize(self, outputStream):
        """serialize the class """
        outputStream.write_unsigned_byte(self.characterSet);
        for idx in range(0, 11):
            outputStream.write_byte( self.characters[ idx ] );
```

`range(0, 11)` only lets the maximum value for `idx` be `10`, which means it only loops through 11 bytes, not 12 (which is the required amount by the DIS standard). The same problem exists in the `parse` method of the `EntityMarking` class, where it only reads in 11 bytes. This causes a loss of information when receiving ESPDUs. 

Furthermore, in the `EntityMarking` class, the initial value for the `self.characters` list [only contains 11 elements](https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L1345).

**Comment by leif81** [comment]
Thanks for the report @DuffyScottC 

From what I'm reading on the linked page it sounds like 11 is the expected length.

http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/64.htm

> The string of characters shall be represented by an 11 element character string.

Do you interpret it differently?

**Comment by DuffyScottC** [comment]
I see where I've gone wrong. I forgot to account for the byte devoted to the **Entity Marking Character Set Field**, which brings the entire entity marking object to a total of 12 bytes, leaving 11 for the entity marking value itself. Please feel free to mark this issue as done and close it. Thank you for your attention and time!
