### ISSUE TITLE
Redundant fields cause serialization/parsing errors

### ISSUE THREAD

**Issue by DuffyScottC** [open-dis/open-dis-python#17]
The `SimulationManagementFamilyPdu` [class](https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L4265) defines two fields:

- `originatingEntityIdD`
- `receivingEntityID`

The following subclasses of `SimulationManagementFamilyPdu`
- `AcknowledgePdu`
- `ActionResponsePdu`
- `ActionRequestPdu`
- `CreateEntityPdu`
- `RemoveEntityPdu`
- `StartResumePdu`
- `StopFreezePdu`

also define two redundant fields:
- `originatingID`
- `receivingID`

This means that the **Originating ID** and **Receiving ID** fields are serialized and parsed twice for these 7 classes. This results in serialization errors when parsing PDUs from external systems, which only serialize these fields once per PDU. 

Notes:
The following classes do not define the redundant fields, and inherit from `SimulationManagementFamilyPdu` without issue (in this regard):
- `CommentPdu `
- `DataPdu`
- `DataQueryPdu`
- `EventReportPdu`
- `SetDataPdu`

**Comment by DuffyScottC** [comment]
The workaround is to remove the extra data from the serialized bytes object when sending DIS messages, and add duplicate data in the appropriate location when receiving DIS messages as bytes objects.

**Comment by leif81** [comment]
Thankyou @DuffyScottC . Would you like to submit a PR?

**Comment by leif81** [comment]
@DuffyScottC can you share sample PDU's related to this? It would help me confirm it's working and increase our test coverage.

**Comment by DuffyScottC** [comment]
What is a PR exactly? :)

**Comment by leif81** [comment]
Pull request :)

I ended up applying the change. Which I why I closed the issue. But if you do have sample PDU's for these it would still be helpful to add better test coverage.
