### ISSUE TITLE
variableParameters

### ISSUE THREAD

**Issue by spriggsy** [open-dis/open-dis-python#2]
Trying to insert variableParameters into my DIS packets for VBS3

Ive managed to create packets and have the Entity display over a network into VBS, this works very well, however Im now trying to get articulation working via variableParameters.

no matter what I set nothing shows up in wireshark.

Has anyone managed to get this to work yet?

many thanks

Spriggsy

**Comment by leif81** [comment]
If it wasn't fixed before, see #9 where we are working on a fix.
