### ISSUE TITLE
Allow for multiple receivers on same UDP address/port

### ISSUE THREAD

**Issue by coderextreme** [open-dis/open-dis-python#25]
Please do something like:

udpSocket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

in examples/dis_receiver.py

to allow for multiple receiver's on same host/port.

I don't know if socket.SO_REUSEPORT is an option or not.  You may choose to use that instead.

Enjoy getting multicasting working!

**Comment by leif81** [comment]
Thanks for the suggestion. This is just an example. But if it's useful for you please go ahead and implement the change, confirm it works and submit a pull request for it. I'll merge it once that is done.

**Comment by brutzman** [comment]
The [open-dis7-java](https://github.com/open-dis/open-dis7-java) project supports multiple receivers, see usages of [DisThreadedNetworkInterface](https://savage.nps.edu/open-dis7-java/javadoc/edu/nps/moves/dis7/utilities/DisThreadedNetworkInterface.html) in the [MV3500 course examples](https://gitlab.nps.edu/Savage/NetworkedGraphicsMV3500/-/tree/master/examples/src/OpenDis7Examples).

**Comment by leif81** [comment]
Closing. This was fixed in MR #38
