### ISSUE TITLE
SignalPdu Not Packing Data Correctly

### ISSUE THREAD

**Issue by japu8876** [open-dis/open-dis-python#31]
Hi!

It looks like the SignalPdu is not packing data correctly (found at [https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L7070](https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L7070)).

In my understanding, the data field of the SignalPdu is supposed to be an array of bytes more or less, based on the code in the __init__ and parse methods. However, the serialize method for the data field implies that each object in the list should have a "serialize" method, which a standard byte would not. 

My recommended change would be to change [https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L7107](https://github.com/open-dis/open-dis-python/blob/master/opendis/dis7.py#L7107)
from 

`anObj.serialize(outputStream)`

to 

`outputStream.write_byte(anObj)`

**Comment by japu8876** [comment]
Looks like this format is repeated often in the file. Some instances appear to track ID objects, which make sense, and others track standard python lists with [], which make less sense, so the whole file might require some grooming for this issue.

**Comment by leif81** [comment]
Thankyou for the report @japu8876 

I realize it's a small change but would you be interested in submitting a pull request for this?

Be aware there's a unit test here that sounds like it needs to be beefed up to catch this issue too if you're interested and able to take that on as part of the pull request?

https://github.com/open-dis/open-dis-python/blob/master/tests/testSignalPdu.py

**Comment by japu8876** [comment]
Hey @leif81,

I could probably work on a pull request for this and try to catch some of the similar errors in a few of the other pdu types, as well as catch the unit-tests. Probably won't be terribly prompt, but I'll give it a go. 

Thanks!
