### ISSUE TITLE
Feature request: Local to Euler angles conversion

### ISSUE THREAD

**Issue by chunky** [open-dis/open-dis-python#33]
I previously was using the java variant of opendis, and it came with a helper function for converting heading/roll/pitch to euler angles for transmission.

I'm using the python version now, and I wish that it had a helper function.

**Comment by leif81** [comment]
This makes sense to me @chunky.

Would you be interested in working on this and providing a pull request?

**Comment by marcdtheking** [comment]
pull request #43 adds this enhancement
