### ISSUE TITLE
Typographical Error in ReceiverPdu

### ISSUE THREAD

**Issue by PeteBlanchard** [open-dis/open-dis-python#39]
In 'dis7.py' there is a minor typo on lines  6914, 6928 and 6939 relating to the 'receivedPower', it was accidentally written as 'receivedPoser'.

**Comment by leif81** [comment]
Thank-you for the report @PeteBlanchard . Would you mind submitting a pull request?

**Comment by PeteBlanchard** [comment]
I don't have permission to create a Pull Request in this repo...

**Comment by PeteBlanchard** [comment]
https://github.com/open-dis/open-dis-python/pull/40
