### ISSUE TITLE
Indentation Errors

### ISSUE THREAD

**Issue by zacharymostowsky** [open-dis/open-dis-python#4]
Hi, I am having trouble running the installation due to indentation errors with the class comments in pythonDis.py. Am I missing a step?

Thanks,
Zach

**Comment by zacharymostowsky** [comment]
Also, the installation specifies python3, yet there are no parenthesis used in print statements.

**Comment by zacharymostowsky** [comment]
I have converted the script but it is too large to upload here. Thanks for your work. I can send it to you if you would like.

**Comment by leif81** [comment]
Hi @zacharymostowsky 

Go ahead and open a pull request with the change if you're comfortable doing that.

**Comment by leif81** [comment]
Reopening this issue. I see what you're saying. It's failing to build for me too with python3. Many errors in `pythonDis.py`.

**Comment by zacharymostowsky** [comment]
@leif81 Hi sorry I have been out of pocket. I see you have closed but I do not see the pythonDis.py file. I will open pull request.

**Comment by leif81** [comment]
I'll explain what happened. 

After reading about your issue that indentation was broken in `pythonDis.py`, I tried to make sense of the other files in the project here. I found the `dis7.py` file nested within the `dis_interactive_simulation` folder. This one is used by the `dis_network_example` referenced in the project `README.md`. I ran it and it worked.

My conclusion from this, and I could be wrong, is that `pythonDis.py` was an older implementation that was broken and had been superceded by `dis7.py`. To remove the confusion, I removed `pythonDis.py`.

Have you tried using `dis7.py` instead?

**Comment by zacharymostowsky** [comment]
HI @leif81, I havent tried yet but will later tonight or tomorrow. The error was occurring during installation of the lib. Perhaps installation needs to change to point at dis7.py. Or if it already does I guess deleting the pythonDis.py will be fine. Also, I realize I dont know how to create a pull request. Happy to email the fixed file over or whatever you prefer.
