### ISSUE TITLE
Parenthesis Wrong in dis7.py

### ISSUE THREAD

**Issue by treybgreen** [open-dis/open-dis-python#6]
Missing parenthesis on read_* function calls

Use `read_([0-9a-z_]+)(?=\r\n)` regex to find (with windows line endings)

Lines found:
- 245
- 250
- 365
- 698
- 740
- 1228
- 1430
- 1496
- 2692
- 3027
- 6017
- 6028

**Comment by leif81** [comment]
Thanks @treybgreen . Would you like to submit a pull-request?
