### ISSUE TITLE
The variable parameters de-serialization is unimplemented and throws the "NameError: name 'null' is not defined" error.

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-python#9]
This is still an issue it seems. The variable parameters de-serialization is unimplemented and throws the "NameError: name 'null' is not defined" error.

_Originally posted by @jmfGE in https://github.com/open-dis/open-dis-python/issues/1#issuecomment-531332250_

**Comment by jmfGE** [comment]
Yes, this is still happening on a fresh install.

**Comment by leif81** [comment]
This should be fixed in https://github.com/open-dis/open-dis-python/commit/1cd5e519fe81fb51cf0cc212fb6479476ff6c1bf

There are some other `null()`'s to clean up still, but this should take care of the variable datum ones.

**Comment by leif81** [comment]
I misunderstood, you meant variable parameter's not variable datum. Reopening.

**Comment by leif81** [comment]
@jmfGE can you retry. I pushed just now what might have fixed it. https://github.com/open-dis/open-dis-python/commit/99b7938a1a9c316dbec085b429d2539d3d4b25bb

**Comment by leif81** [comment]
@jmfGE if you could share a pdu that was causing this issue that would help too. We have very few sample dis7 pdu's to test against.

**Comment by jmfGE** [comment]
This fixed the issue for me, thanks! I was using this file captured from VR-Forces. I did notice when using wireshark that the output size of the PDU was much smaller than size of the file. This results in VR-Forces complaining about a bad packet size. I'm not sure if it's a bug or something wrong on my end.
[uav.zip](https://github.com/open-dis/open-dis-python/files/3664720/uav.zip)

```
import socket
import time
import sys

from opendis.DataInputStream import DataInputStream
from opendis.DataOutputStream import DataOutputStream

from opendis.dis7 import EntityStatePdu
from io import BytesIO
from opendis.RangeCoordinates import GPS
import opendis.PduFactory as pduFactory


UDP_PORT = 3000
DESTINATION_ADDRESS = "127.255.255.255"

def test():
    global DESTINATION_ADDRESS
    global UDP_PORT
    udpSocket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    ent = None
    with open("uav.bin",'rb') as fl:
        data = fl.read()
        print(len(data))
        ent = pduFactory.createPdu(data)
    ent.entityID.entityID = 101
    name = ['U','A','V',' ', '5']
    for i in range(len(name)):
        ent.marking.characters[i] = ord(name[i])

    xPos = ent.entityLocation.x
    yPos = ent.entityLocation.y
    zPos = ent.entityLocation.z
    while True:
        memoryStream = BytesIO()
        outputStream = DataOutputStream(memoryStream)
        ent.entityLinearVelocity.y = 500.0
        
        ent.serialize(outputStream)
        data = memoryStream.getvalue()
        udpSocket.sendto(data, (DESTINATION_ADDRESS, UDP_PORT))
        time.sleep(1.0)

if __name__ == "__main__":
    test()
```

**Comment by leif81** [comment]
@jmfGE thank-you this is helpful.

The `uav.bin` file is 1200 bytes, what I'm seeing within it are two packets:
1. The first is an EntityState PDU that is 240 bytes. 
2. The second is an Attribute PDU that is 960 bytes.

**Comment by jmfGE** [comment]
That does. Wireshark is telling me the combined PDU packets are 1200 bytes, but [this document](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/29.htm) says that my entity PDU should be 1280 bytes. Am I missing something on my end?

**Comment by leif81** [comment]
Oh I see, the 1280 is in bits, so 160 bytes. If the packet has articulation parameters it will be larger.
